apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: go-test
  labels:
    app: go-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test
  template:
    metadata:
      labels:
        app: go-test
    spec:
      serviceAccountName: my-test-sa
      containers:
      - name: go-test
        image: jaimeyh/inframanager:latest
        ports:
        - containerPort: 9090