kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: mis-pruebas
  name: prueba-go-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
  - delete
  - create